#!/usr/bin/env zsh

# logging
function action { print -P "%B%F{yellow}action%f%b: $1" }
function info   { print -P "%B%F{blue}info%f%b: $1" }
function error  { print -P "%B%F{red}error%f%b: $1" }

# add hooks path
git config core.hooksPath .git-hooks

info 'installed hooks'
